### ISSUE TITLE
Release new version on PyPI

### ISSUE THREAD

**Issue by voronind** [OCA/openupgradelib#210]
Please release on PyPI

**Comment by pedrobaeza** [comment]
The publishing is not working due to Travis/PyPi changes, but if you want to investigate about that, you can contribute it with that. Anyway, it's not needed. Just do:
```
pip install --ignore-installed git+https://github.com/OCA/openupgradelib.git@master
```
and you'll always get latest version. In fact, that one is the recommended method, as this library is very dynamic and can't release so often.

Closing as there's a workaround that is actually the recommended method.

**Comment by voronind** [comment]
I don't need latest version. I need fixed version.  
Travis deploy looks good. Try to tag commits.

**Comment by pedrobaeza** [comment]
The latest is the stable one. There are no development commits, so no need of tags.
