### ISSUE TITLE
Publish version 3.0 to pypi

### ISSUE THREAD

**Issue by mileo** [OCA/openupgradelib#234]
https://pypi.org/project/openupgradelib/#history

**Comment by celm1990** [comment]
Hello I have the same curiosity because the latest version is not published in `pip`

@pedrobaeza can you help me with your comments??

**Comment by pedrobaeza** [comment]
There are constant changes in the library, and doing a publish to Pypi for each one is not possible, so there's always the risk of having an outdated version using pypi version, so better to use github code one. That's linked to the fact that the credentials for uploading are not working right now.

**Comment by rousseldenis** [comment]
> There are constant changes in the library, and doing a publish to Pypi for each one is not possible, so there's always the risk of having an outdated version using pypi version, so better to use github code one. That's linked to the fact that the credentials for uploading are not working right now.

I agree, but having a library not updated since 2018...

Moreover, writing specifically your dependency with @master is counterproductive. I'm more on solving the publishing problem to avoid such writings : https://github.com/OCA/bank-payment/pull/852/commits/4cd04a3dcc26e9b18cab8de492586f3716ad11bb#diff-4d7c51b1efe9043e44439a949dfd92e5827321b34082903477fd04876edb7552R3

@sbidoul @simahawk Could we envisage a solution here?

**Comment by simahawk** [comment]
I don't know what is the main blocker but having a push on pypi every time we get a version bump is the way to go.
@sbidoul could we use the bot? Otherwise we could setup [GH actions](https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/).

**Comment by sbidoul** [comment]
#243 should make it trivial to publish releases.
