### ISSUE TITLE
Switch from pool to env for version 10

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/openupgradelib#65]
In version 10, there's no more `pool` object, so we need to change a lot of openupgradelib functions to adapt to the new architecture. The problem here is the backwards compatibility. I think right now in several possibilities:

* Create a separate branch for openupgradelib v10 version. This one is the cleanest option.
* Add keyword arguments for passing `env` and adapt code to detect not null values.
* Some kind of decorator to change the signature.

What do you think, @hbrunn, @StefanRijnhart, @jbeficent ?

**Comment by hbrunn** [comment]
the registry object still exists: https://github.com/OCA/OCB/blob/10.0/odoo/modules/registry.py#L23 and probably won't go away any time soon

But passing environments where we would pass registries now would be a quite welcome change. We can't do this everywhere, because the Environment context is only created quite late compared to the registry.

Looking through the code, I only count four instances of general functions that take a registry at all (https://github.com/OCA/openupgradelib/blob/master/openupgradelib/openupgrade.py#L477, https://github.com/OCA/openupgradelib/blob/master/openupgradelib/openupgrade.py#L1098, https://github.com/OCA/openupgradelib/blob/master/openupgradelib/openupgrade.py#L587, https://github.com/OCA/openupgradelib/blob/master/openupgradelib/openupgrade.py#L539). For those few, I think we can easily make them autodetect what we got. For the version specific ones, we simply can decide that from 9.0 on, a standard openupgradelib signature should be `(env, ....)` and we're done.

Note that we did already decide that the migrate decorator will pass an env starting from 10: https://github.com/OCA/openupgradelib/blob/master/openupgradelib/openupgrade.py#L1043-L1046

**Comment by pedrobaeza** [comment]
Cool to see that the registry object is still there. At least we can decide what we do without the pressure of changing it. We can certainly detect that pool is an environment detecting something or directly passing another argument.

**Comment by hbrunn** [comment]
we finished this argument, right?
